// Hand-written idiomatic wrapper around the generated `NativeMethods`
// P/Invoke bindings (NativeMethods.g.cs). This file is NOT regenerated by
// `sdk/build.rs` -- only NativeMethods.g.cs is, from `sdk/src/ffi.rs`.

using System;
using System.Text;

namespace NextTabletDriver.Sdk
{
    /// <summary>Driver mapping mode. Mirrors the Rust `DriverMode` enum.</summary>
    public enum DriverMode : byte
    {
        Absolute = 0,
        Relative = 1,
    }

    /// <summary>Managed, decoded snapshot returned by <see cref="NtdClient.PollState"/>.</summary>
    public readonly struct TabletState
    {
        public bool IsConnected { get; }
        public byte Status { get; }
        public float U { get; }
        public float V { get; }
        public float ScreenX { get; }
        public float ScreenY { get; }
        public int Pressure { get; }
        public int TiltX { get; }
        public int TiltY { get; }
        public byte Buttons { get; }
        public bool IsDown { get; }
        public bool Eraser { get; }
        public string DeviceName { get; }
        public ushort Vid { get; }
        public ushort Pid { get; }
        public DriverMode Mode { get; }
        public float ActiveAreaX { get; }
        public float ActiveAreaY { get; }
        public float ActiveAreaW { get; }
        public float ActiveAreaH { get; }
        public float ActiveAreaRotation { get; }
        public uint ConfigVersion { get; }

        internal unsafe TabletState(in NtdState native)
        {
            IsConnected = native.is_connected;
            Status = native.status;
            U = native.u;
            V = native.v;
            ScreenX = native.screen_x;
            ScreenY = native.screen_y;
            Pressure = native.pressure;
            TiltX = native.tilt_x;
            TiltY = native.tilt_y;
            Buttons = native.buttons;
            IsDown = native.is_down;
            Eraser = native.eraser;
            Vid = native.vid;
            Pid = native.pid;
            Mode = (DriverMode)native.mode;
            ActiveAreaX = native.active_area_x;
            ActiveAreaY = native.active_area_y;
            ActiveAreaW = native.active_area_w;
            ActiveAreaH = native.active_area_h;
            ActiveAreaRotation = native.active_area_rotation;
            ConfigVersion = native.config_version;

            var length = (int)Math.Min(native.device_name_len, NtdClient.DeviceNameCapacity);
            fixed (byte* namePtr = native.device_name)
            {
                DeviceName = length > 0 ? Encoding.UTF8.GetString(namePtr, length) : string.Empty;
            }
        }
    }

    /// <summary>Thrown when a native `ntd_*` call returns a non-`NTD_OK` error code.</summary>
    public sealed class NtdException : Exception
    {
        public int ErrorCode { get; }

        private NtdException(int errorCode, string message) : base(message)
        {
            ErrorCode = errorCode;
        }

        internal static NtdException FromErrorCode(int code, string operation)
        {
            var reason = code switch
            {
                NtdClient.ErrHidInitFailed => "the HID backend failed to initialize",
                NtdClient.ErrNotInitialized => "the SDK is not initialized",
                NtdClient.ErrNullPointer => "a required output pointer was null",
                NtdClient.ErrInvalidArgument => "an argument was outside its valid range",
                NtdClient.ErrCommandFailed => "the current HID owner process could not be reached",
                NtdClient.ErrPanic => "the native call panicked",
                _ => $"unknown error code {code}",
            };
            return new NtdException(code, $"{operation} failed: {reason}");
        }
    }

    /// <summary>
    /// Owns one embedded NextTabletDriver engine instance for the lifetime of
    /// this object. The native engine is a single global instance per loaded
    /// <c>ntd_sdk</c> library, so construct exactly one <see cref="NtdClient"/>
    /// per process (or per plugin context) and <see cref="Dispose"/> it only
    /// when the host is done with tablet input for good.
    /// </summary>
    public sealed class NtdClient : IDisposable
    {
        internal const int Ok = 0;
        internal const int ErrHidInitFailed = -1;
        internal const int ErrNotInitialized = -2;
        internal const int ErrNullPointer = -3;
        internal const int ErrInvalidArgument = -4;
        internal const int ErrCommandFailed = -5;
        internal const int ErrPanic = -6;

        internal const uint DeviceNameCapacity = 64;

        private bool _disposed;

        /// <summary>
        /// Starts the embedded engine: becomes the HID owner if no other
        /// process currently is one, otherwise starts in reader mode and
        /// mirrors the real owner's state.
        /// </summary>
        /// <exception cref="NtdException">The native engine failed to start.</exception>
        public NtdClient()
        {
            var result = NativeMethods.ntd_init();
            if (result != Ok)
            {
                throw NtdException.FromErrorCode(result, nameof(NtdClient));
            }
        }

        /// <summary>
        /// This build's FFI ABI version -- compare against the version this
        /// binding was generated for to detect a mismatched native library.
        /// </summary>
        public static uint AbiVersion => NativeMethods.ntd_sdk_abi_version();

        /// <summary>Reads the current tablet + config snapshot.</summary>
        public unsafe TabletState PollState()
        {
            ThrowIfDisposed();

            var native = default(NtdState);
            var result = NativeMethods.ntd_poll_state(&native);
            if (result != Ok)
            {
                throw NtdException.FromErrorCode(result, nameof(PollState));
            }

            return new TabletState(in native);
        }

        /// <summary>Sets the driver mapping mode.</summary>
        public void SetMode(DriverMode mode)
        {
            ThrowIfDisposed();

            var result = NativeMethods.ntd_set_mode((byte)mode);
            if (result != Ok)
            {
                throw NtdException.FromErrorCode(result, nameof(SetMode));
            }
        }

        /// <summary>
        /// Sets the active mapping area, in millimeters (clamped to the
        /// current device's physical surface).
        /// </summary>
        public void SetActiveArea(float x, float y, float w, float h, float rotation)
        {
            ThrowIfDisposed();

            var result = NativeMethods.ntd_set_active_area(x, y, w, h, rotation);
            if (result != Ok)
            {
                throw NtdException.FromErrorCode(result, nameof(SetActiveArea));
            }
        }

        private void ThrowIfDisposed()
        {
            if (_disposed)
            {
                throw new ObjectDisposedException(nameof(NtdClient));
            }
        }

        /// <summary>Stops the embedded engine and joins its background thread.</summary>
        public void Dispose()
        {
            if (_disposed)
            {
                return;
            }

            NativeMethods.ntd_shutdown();
            _disposed = true;
        }
    }
}
