[package]
name = "hawku_smoothing"
version = "1.0.0"
publish = false
edition = "2024"
authors = ["X9VoiD <https://github.com/X9VoiD>"]
description = "Hawku Low-pass Exponential Smoothing Filter"

[lib]
crate-type = ["cdylib"]

[dependencies]
ntd_plugin_api = { path = "../../sdk/plugin_api" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
